# Generated by Django 3.1 on 2020-09-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claims',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Insured_Name', models.CharField(max_length=50)),
                ('Buyer_name', models.CharField(max_length=50)),
                ('PAN', models.CharField(max_length=20)),
                ('Default_Amt', models.CharField(max_length=20)),
                ('Limit_Type', models.CharField(default=0, max_length=20)),
                ('Report_date', models.DateField()),
                ('Claim_status', models.CharField(choices=[('NNP', 'NNP'), ('Claim', 'Claim'), ('Claim Under Process', 'Claim Under Process'), ('Repudiated', 'Repudiated'), ('Disputed', 'Disputed'), ('Paid and Closed', 'Paid and Closed'), ('Overdue Cleared', 'Overdue Cleared'), ('Overdue Cleared and Reinstated', 'Overdue Cleared and Reinstated')], default='NNP', max_length=1000)),
                ('Limit_Withdrawal', models.DateField()),
                ('Claim_Extension', models.DateField()),
                ('Claim_Extension_Number', models.CharField(choices=[('NIL', 'NIL'), ('FIRST', 'FIRST'), ('SECOND', 'SECOND'), ('THIRD', 'THIRD'), ('FOURTH', 'FOURTH'), ('FIFTH', 'FIFTH')], default='NIL', max_length=50)),
            ],
            options={
                'verbose_name': 'Claim',
            },
        ),
        migrations.CreateModel(
            name='CreditLimits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Insured_Name', models.CharField(max_length=50)),
                ('PAN', models.CharField(max_length=20)),
                ('Insured_ref', models.CharField(max_length=20)),
                ('Buyer_name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=200)),
                ('CLA', models.CharField(max_length=20)),
                ('CLD', models.CharField(max_length=20)),
                ('CLA_Date', models.DateField(auto_now=True)),
                ('CLD_Date', models.DateField(auto_now=True)),
                ('Effective_Date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CreditLimit',
            },
        ),
    ]
