# Generated by Django 3.1 on 2020-09-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaimsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditlimits',
            name='CLA_Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='creditlimits',
            name='CLD_Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='creditlimits',
            name='Effective_Date',
            field=models.DateField(),
        ),
    ]
