# Generated by Django 3.1 on 2020-08-31 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClaimsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claims',
            old_name='Buyername',
            new_name='Buyer_name',
        ),
        migrations.RenameField(
            model_name='claims',
            old_name='DEFAULT',
            new_name='Default_Amt',
        ),
        migrations.RenameField(
            model_name='claims',
            old_name='InsuredName',
            new_name='Insured_Name',
        ),
    ]
