# Generated by Django 3.1 on 2020-08-31 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaimsApp', '0002_auto_20200831_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='claims',
            name='Limit_Type',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
