# Generated by Django 3.1 on 2020-09-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaimsApp', '0002_auto_20200913_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditlimits',
            name='CLA_Date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='creditlimits',
            name='CLD_Date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='creditlimits',
            name='Effective_Date',
            field=models.CharField(max_length=20),
        ),
    ]
