# Generated by Django 3.1 on 2020-09-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaimsApp', '0003_auto_20200913_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditlimits',
            name='CLA_Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='creditlimits',
            name='CLD_Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='creditlimits',
            name='Effective_Date',
            field=models.DateField(),
        ),
    ]
