# Generated by Django 3.1 on 2020-09-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaimsApp', '0003_claims_limit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='claims',
            name='Date_of_reporting',
            field=models.DateField(auto_now=True),
        ),
    ]
