# Generated by Django 3.1 on 2020-09-04 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClaimsApp', '0004_claims_date_of_reporting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claims',
            old_name='Date_of_reporting',
            new_name='Report_date',
        ),
    ]
