# Generated by Django 3.1 on 2020-09-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaimsApp', '0005_auto_20200904_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claims',
            options={'verbose_name': 'Claim'},
        ),
        migrations.AddField(
            model_name='claims',
            name='Claim_status',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
