# Generated by Django 3.1 on 2020-09-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaimsApp', '0005_auto_20200913_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditlimits',
            name='Buyer_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='creditlimits',
            name='Insured_Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='creditlimits',
            name='Insured_ref',
            field=models.CharField(max_length=100),
        ),
    ]
