# Generated by Django 3.1 on 2020-09-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaimsApp', '0006_auto_20200913_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditlimits',
            name='CLA',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='creditlimits',
            name='CLD',
            field=models.CharField(max_length=100),
        ),
    ]
