# Generated by Django 3.1 on 2020-09-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaimsApp', '0006_auto_20200906_1032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claims',
            options={},
        ),
        migrations.AlterField(
            model_name='claims',
            name='Report_date',
            field=models.DateField(),
        ),
    ]
