# Generated by Django 3.1 on 2020-09-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaimsApp', '0007_auto_20200906_1112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claims',
            options={'verbose_name': 'Claim'},
        ),
        migrations.AlterField(
            model_name='claims',
            name='Claim_status',
            field=models.CharField(default='NNP', max_length=20),
        ),
    ]
