# Generated by Django 3.1 on 2020-09-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaimsApp', '0007_auto_20200913_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditlimits',
            name='PAN',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
