# Generated by Django 3.1 on 2020-09-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaimsApp', '0008_auto_20200913_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditlimits',
            name='Buyer_name',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='creditlimits',
            name='CLA',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='creditlimits',
            name='CLD',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='creditlimits',
            name='Insured_ref',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='creditlimits',
            name='PAN',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
