# Generated by Django 3.1 on 2020-09-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaimsApp', '0008_auto_20200906_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claims',
            name='Claim_status',
            field=models.CharField(choices=[('Claim', 'Claim')], default='NNP', max_length=20),
        ),
    ]
