# Generated by Django 3.1 on 2020-09-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaimsApp', '0012_auto_20200906_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claims',
            name='Claim_status',
            field=models.CharField(choices=[('NNP', 'NNP'), ('Claim', 'Claim'), ('Claim_Under_Process', 'Claim Under Process'), ('Disputed', 'Disputed'), ('Paid and Closed', 'Paid and Closed')], default='NNP', max_length=20),
        ),
    ]
