# Generated by Django 3.1 on 2020-09-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaimsApp', '0014_claims_limit_withdrawal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claims',
            name='Buyer_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='claims',
            name='Insured_Name',
            field=models.CharField(max_length=50),
        ),
    ]
