# Generated by Django 3.1 on 2020-09-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClaimsApp', '0015_auto_20200907_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='claims',
            name='Claim_Extension',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='claims',
            name='Claim_status',
            field=models.CharField(choices=[('NNP', 'NNP'), ('Claim', 'Claim'), ('Claim_Under_Process', 'Claim Under Process'), ('Disputed', 'Disputed'), ('Paid and Closed', 'Paid and Closed')], default='NNP', max_length=1000),
        ),
        migrations.AlterField(
            model_name='claims',
            name='Limit_Withdrawal',
            field=models.DateField(),
        ),
    ]
